cp -r src/adservice/* codecommit/adservice-repo/
cp -r src/cartservice/* codecommit/cartservice-repo/
cp -r src/checkoutservice/* codecommit/checkoutservice-repo/
cp -r src/currencyservice/* codecommit/currencyservice-repo/
cp -r src/emailservice/* codecommit/emailservice-repo/
cp -r src/frontend/* codecommit/frontend-repo/
cp -r src/paymentservice/* codecommit/paymentservice-repo/
cp -r src/productcatalogservice/* codecommit/productcatalogservice-repo/
cp -r src/recommendationservice/* codecommit/recommendationservice-repo/
cp -r src/shippingservice/* codecommit/shippingservice-repo/
