aws ecr delete-repository --repository-name adservice --force
aws ecr delete-repository --repository-name cartservice --force
aws ecr delete-repository --repository-name emailservice --force
aws ecr delete-repository --repository-name productcatalogservice --force
aws ecr delete-repository --repository-name recommendationservice --force
aws ecr delete-repository --repository-name currencyservice --force
aws ecr delete-repository --repository-name frontend --force
aws ecr delete-repository --repository-name paymentservice --force
aws ecr delete-repository --repository-name shippingservice --force
aws ecr delete-repository --repository-name checkoutservice --force
